# This file allows you to configure the Dart analyzer.
#
# The commented part below is just for inspiration. Read the guide here:
#   https://www.dartlang.org/guides/language/analysis-options

 analyzer:
   exclude:
     - web/common/schemas/**
 linter:
   rules:
     - cancel_subscriptions
     - omit_local_variable_types
     - prefer_final_locals
     - prefer_is_empty
     - prefer_is_not_empty
     - annotate_overrides
     - valid_regexps
     - avoid_returning_null
     - overridden_fields
     - prefer_contains
