name: 'palace'
version: 0.0.1
description: An absolute bare-bones web app.
#author: derri <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: 'any'

dependencies:
  quiver: 'any'
  test: 'any'
  args: 'any'
  http_server: 'any'
  password_hash: 'any'
  objectdb: 'any'
  protoc_plugin: 'any'
  protobuf: 'any'
  stagexl: 'any'

dev_dependencies:
  pedantic: ^1.8.0
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
